### PR TITLE
(GH-12) Add Travis file

### PR DESCRIPTION
**Pull request by jpogran**
Add travis file, using https://code.visualstudio.com/docs/extensions/testing-extensions#_running-tests-automatically-on-travis-ci-build-machines as example

### CODE REVIEW

**Comment by glennsarti** [comment]
In Appveyor you may want to tick the "Ignore branches with no appveyor" checkbox.

**Comment by glennsarti** [comment]
`cd client` is in there twice

**Comment by jpogran** [comment]
Yes, was unsure of state. However, that's not what failing

**Comment by jpogran** [comment]
This is fixed, had to use https://github.com/Microsoft/vscode/blob/master/.travis.yml as an example

**Pull request merged**
