### PR TITLE
(GH-#187) Add a stdio mode to the language server

### PR DESCRIPTION
**Pull request by ace13**
I'm unsure on how to add a test for this feature, but if someone has a good suggestion for that then I'll happily write one.

### CODE REVIEW

**Comment by glennsarti** [comment]
Thanks for the PR @ace13 .  I'll review it soon.

**Comment by glennsarti** [comment]
@ace13  Are you ok with me adding on some commits to this PR?

**Comment by glennsarti** [comment]
Couple of things I see
* Client detection is a bit off so the timeout doesn't work yet
* I'll have a go at some basic tests for both stdio and tcp based servers
* I want to add a failure if you specify --stdio and --debug=STDOUT as they're not compatible

**Comment by ace13** [comment]
I didn't touch any of that client detection, since there's technically a client through the entirety of the servers lifetime. Not sure if that's the right way to go about it though, or if actually tracking a client is more appropriate.

I also did add a small mode for specifying `--debug=STDERR` during my testing, but didn't want to commit it as part of this feature addition as it's completely irrelevant to the feature itself. But yeah, should probably have an error for debug and stdio mode at the same time. 

And I don't particularly mind if you want to add some commits as well.

**Comment by glennsarti** [comment]
Yeah...just trying to think, if the language server is started as a child process, and the parent dies, then the child is orphaned.  Will the language server be able to detect that ... I'll see if I can set that up as testing scenario.

**Comment by glennsarti** [comment]
Yup...the language server remains if the parent dies.  At least on Windows :-(

**Comment by glennsarti** [comment]
On second thoughts.  I think I'm being too defensive.  Will just write some tests and then merge it.

**Comment by glennsarti** [comment]
Hrmm...so the TCP server code seems to be broken.  Good news is, my tests were failing because of it!  I'll keep working on it.  Thanks @ace13

**Comment by glennsarti** [comment]
@ace13 You ok with my additional commits?

**Comment by ace13** [comment]
No issues with them, looks fine to me.

**Pull request merged**
